baseURL: 'https://renn.es/'
languageCode: 'en'
title: "Renn.es"

theme: "tarneo.fr"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "English"
      url: "/"
      weight: 1
    - name: "Français"
      url: "/fr/"
      weight: 2

params:
  favicon: "penguin.png"
  description: "Renn.es is a tilde community running on Gentoo Linux."
