baseURL: 'https://renn.es/'
languageCode: 'fr-fr'
defaultContentLanguage: 'fr-fr' # For date internationalization
title: "Renn.es"

theme: "rennes"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  favicon: "penguin.png"
  description: "Un traîneau d'avance sur les GAFAM"
  navbar: true
  footer: true
  logo: "logo.svg"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Tutoriels"
      url: "/tutoriels"
      weight: 2
  footer:
    - name: "Statuts"
      url: "/textes/statuts"
      weight: 1
    - name: "Règlement intérieur"
      url: "/textes/reglement"
      weight: 2
    - name: "CGU"
      url: "/textes/cgu"
      weight: 3
    - name: "Sécurité"
      url: "/textes/securite"
      weight: 4
    - name: "Mentions légales"
      url: "/legal/"
      weight: 5
    - name: "Clés PGP"
      url: "/keys/"
