baseURL: 'https://renn.es/'
languageCode: 'en'
title: "Renn.es"

menu:
  main:
    - name: "English"
      url: "/"
      weight: 1
    - name: "Français"
      url: "/fr/"
      weight: 2

params:
  favicon: "penguin.png"
  description: "Renn.es is a non-profit and open shared computer system with a small user base running on Arch Linux."
