baseURL: 'https://renn.es/'
languageCode: 'en'
title: "Renn.es"

theme: "renny"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  favicon: "penguin.png"
  description: "Renn.es is a collective which provides various services, ranging from email to web hosting."
  navbar: false
