baseURL: 'https://renn.es/'
languageCode: 'en'
defaultContentLanguage: 'fr-fr' # For date internationalization
title: "Renn.es"

theme: "renny"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  favicon: "penguin.png"
  description: "Renn.es is a collective which provides various services, ranging from email to web hosting."
  navbar: true

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Services"
      url: "/services/"
      weight: 2
