baseURL: 'https://renn.es/'
languageCode: 'en'
title: "Renn.es"

theme: "tarneo.fr"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  favicon: "penguin.png"
  description: "Renn.es is a tilde community running on Debian Linux."
  navbar: false
